language: python
sudo: required
services:
  - docker
env:
  global:
    - secure: P6c1spkY+mxyZKX+OIaUzcoJLLfZCxBEj6e/ZVThO6u4IGOoFajceQ/iXsaXLtoBhSqkbVMNs1YWqGFD8MLhBvrTY3DRQAKvavT38Z1tM5Vd91KzSgZkNRbNMswRu09STop2Eb0rl9iK81i+Hgsq3KTXtbOMrMCqJtpKOlWasvF5ZrMmwS6DXyIPW4ow671O4s2yKtkfXt3NGiX+GBlTE4ed6BJcrZ072HVR2uCg4vb1kPB5CH3Mz+r7bbVU7EY8QsUke20ZtHX1c3NErN5RSHrbLKujIeo21gdntv8nVldVX5iYMbzStqJyBJ8tmesstv3XUfMkAHnB0CRdVLm1O2fVMDnYehEWxbtGbBBpcrOG/T3U4FPKffB3Ao0uIh+k2uqPBdP4mEcqd6rEo7PdSlC/p6zNnw+JpqdQ0utHwBhIbeELCi1pytKRbHI4G+7UlJZE+Tmw/BHnPDzQs9HjZVyzDjVarfS2xpdhrogGJlCkpxz3eXWN8WbsTdUExZaiFGeZ41TgIyaGaEkrMXA3iLJRzI3VfUAueSUt1VVq8KKHLa1qKt2vn0Dx/3oXTTRz4Nl9Z5sayi68XccVbyjbvv/0SDGQAvd/7/ZhlidW9xPbJtjc6CG6UWRTRkm6bSJQhQ1lq1VsYmPtzCqXqIVNXKINS/j3CvvKla0PejQp9U4=
    - secure: 22S/8zpvjldEjolbeMBLnq/0iXBKMVjFVqVYVEzZbBgdvnbhTWwa9B9mLVHhOwnl8RNFB2P0qTI+5pz8SqL9tf4G+hw/h0bG7OW8cSnMwyp07yNbZrn/9cxzrWhlQn3mLxeOFiNDM1eZ5BmTFJca3roF4KrZ3OVq59ibmCAhe8KY+TqOuf5600nGmDHtVtEQxApyIUUm9VQAKrj1Y0ihJGLF5RLSXODKXTGn2nEfRxrDDf2JYgZWrQ9cCkRC/NpNGpaaXyPC8SXp1UtPAKsDrfVjnh5iejMRLxWTy7oFkrM3DP8wCBCGeiVTyF02mOR0U5ykzd8ydkBeWgSQx1fCXKHXXyzzkqgLvYcnpfPY3UEXqjEO1OnWDsA8rbzgyvQzvuWDP35Yt221t6bo7uqcySMZl1QA+XEnXFVgAroY//7Owy5PNlX5HCWIl0xRBktBNfsZIy/Ff56eqglqL8nE5V4cqISqF5FYQwsO+kQWBFynQit2uUvphEc6ptJPng6qeOtDEd8roo5YcapfuVzphNzwQh713B8cfnAwFrgkfgOo52Ok1Qtn2/4t/97XghFe1Ui9oXgdQ++VZ4KiJgA/dlmXSTyWUI2+nTxSOjNVlv0VZodza85wF7dDFbLLYtziCqx+g+LQdaJFB3ww/ro/W9yLM9ze89xlxDfdR92Rz0M=
    - secure: oGZRRq2qRwO8UDimsfTwxiAhWYDKM/tR81AmTUaypra6qKJ/fU6dWjYrfQ7tw4BvRyR7wOCr2dV0J2D20G1e/QbtVASJzyU4crNcmz8p7Xe1ClVn6dPOEtp9cLjif4A0tMGZOxhEnb4gvv+yXKPUQRcSC3vgfPKVbHQJQuFGa87VpmXdwsKIIMNmq35rrjHdMbAhAsRaLYfXdeJynSvsshrmG1B5AvcIIQgTIHl+524500caX852O88vzzbyidP2eWTWz4ea3p+fpNtUahLHiQPi+oLjmqECbVdMi92qEuzySnIhjcxdItgwSa2IHCfStW+yPxvrcH7UWtOcjX9lM5+gPYsi0t6l6wuVObPVqigY9qCOfMhQtw2DZN9qRoVwQQeC9sGmyivK+hGYXSahtuGF+9C3AVT7SIsgRGqVWPh73r+laMCRnSfi1+hyBy7gKTsboT5hx+rFSVAzuNCoXooJTrMeM1QQEGOgfHNPrYR8idUnLRq2xMtsAgSN2NU0zQxDJV+CJFEZRq9Ly0JQCylLFtMRUDfH16jb6VMwtdkvfpMoDslkZ9me5p126J8vdSlgr7ceH1sM3wul8uILFT4ZVPNeVRyqFP1OFNQpa3YA+sXMzMzshEVDw4NVdolQcMoBC83UkzSsLJQUnOUEVh1mhuFdyVnQuWykndPS7Ac=
    - PROJECT_NAME=quicksectx
    - GITHUB_REPO_NAME=jianlins/quicksectx
    - CONDA_PKG_NAME_PY=quicksectx
    - PYPI_LOGIN=jianlins
    - PY36="cp36-cp36m"
install:
  - docker pull quay.io/pypa/manylinux1_x86_64
  - docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd && yum update -y && mkdir /wheelhouse &&
    yum install zlib-devel libxml2-devel -y && pwd &&
    git clone https://github.com/jianlins/quicksectx.git && cd quicksectx && ls &&
    /opt/python/${PY36}/bin/pip wheel . -w /wheelhouse &&
    auditwheel repair /wheelhouse/quicksectx-${VERSION}-${PY36}-linux_x86_64.whl -w /wheelhouse"
  - docker cp aaa:/wheelhouse/quicksectx-${VERSION}-${PY36}-manylinux1_x86_64.whl ./
script:
  - ls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: lwm3hk0SbDAHXNz8oHRhfD9DJlR1UJguU7KaB6sJlnRIqmHV5dleEy2FrFCKVUlanzWVVnV08AOSMpHx3n8ebnlaWt61IV9Y3yyZBs5ye/UoZGPCduse9AwefMvBUA+LR1SAtHe+fmV3+g/DnY4LEWbOXR6njK79q6+Qza7VtU5lqvQmlN86Foipb5wdKgT7zz3WCzjnXn/CJLPFkHqvM2W/9mG2+3zTHXNA7Ext5JXGOI+3qpQ5eQkgekbQqUK0ZDJBo9zk/BbiNIv1sT9O7qb1on2Jmy/nOZFpEL2x6EIffDEF7Pk2Ve117/r0ubGUPek2qIl0X/sbqJNnfmpDlYgHieR2006XAWzouitCyDsESUJAwST4atoAMyMnCkwZl0j/9vrX1b/czHdW98KPEr4riCsKN7UsmxIU0bSKrXxDy8WR8IAJDZMJwaGxiRQzazAGkaC6rdGWv8oVNPy9ynE/479RAXSbUHO2HxfOATNcS6IX72+aO8n8E0ChK5L39v4REUexq77xxrRydT6EVZA5edIZCr+PXbUqy1MI4ICnuzwhJiKSZ/R7uaUTDb8yu8NgpTQv2xTNiHt2sSRZmRa8yQw5qRO8NhHij9Ex5sInNoOLrHP1tskTovaxMJn7+dnaH4gF3R57b3sNX7d60ljZgfaBxJMMdgmtPRvbLRU=
  on:
    repo: ${GITHUB_REPO_NAME}
    #    tags: true
#    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 3.6 && $TRAVIS_OS_NAME == linux"
  skip_existing: true