sudo: required
services:
  - docker
env:
  global:
#    - VERSION="0.7.1.post6"
    - PY36="cp36-cp36m"
before_install:
  - docker pull quay.io/pypa/manylinux1_x86_64
  - docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd && yum update -y && mkdir /wheelhouse &&
    yum install zlib-devel libxml2-devel -y &&
    mv /usr/lib/libxml2.a /usr/lib/libxml2.a.org && mv /usr/lib64/libxml2.a /usr/lib64/libxml2.a.org &&
#    git clone -b ${VERSION} git://github.com/igraph/python-igraph && cd python-igraph &&
    git clone git@github.com:jianlins/quicksectx.git && cd quicksectx &&
    /opt/python/${PY36}/bin/pip wheel . -w /wheelhouse &&
    auditwheel repair /wheelhouse/quicksectx-${VERSION}-${PY36}-linux_x86_64.whl -w /wheelhouse"
  - docker cp aaa:/wheelhouse/quicksectx-${VERSION}-${PY36}-manylinux1_x86_64.whl ./
script:
  - ls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: lwm3hk0SbDAHXNz8oHRhfD9DJlR1UJguU7KaB6sJlnRIqmHV5dleEy2FrFCKVUlanzWVVnV08AOSMpHx3n8ebnlaWt61IV9Y3yyZBs5ye/UoZGPCduse9AwefMvBUA+LR1SAtHe+fmV3+g/DnY4LEWbOXR6njK79q6+Qza7VtU5lqvQmlN86Foipb5wdKgT7zz3WCzjnXn/CJLPFkHqvM2W/9mG2+3zTHXNA7Ext5JXGOI+3qpQ5eQkgekbQqUK0ZDJBo9zk/BbiNIv1sT9O7qb1on2Jmy/nOZFpEL2x6EIffDEF7Pk2Ve117/r0ubGUPek2qIl0X/sbqJNnfmpDlYgHieR2006XAWzouitCyDsESUJAwST4atoAMyMnCkwZl0j/9vrX1b/czHdW98KPEr4riCsKN7UsmxIU0bSKrXxDy8WR8IAJDZMJwaGxiRQzazAGkaC6rdGWv8oVNPy9ynE/479RAXSbUHO2HxfOATNcS6IX72+aO8n8E0ChK5L39v4REUexq77xxrRydT6EVZA5edIZCr+PXbUqy1MI4ICnuzwhJiKSZ/R7uaUTDb8yu8NgpTQv2xTNiHt2sSRZmRa8yQw5qRO8NhHij9Ex5sInNoOLrHP1tskTovaxMJn7+dnaH4gF3R57b3sNX7d60ljZgfaBxJMMdgmtPRvbLRU=
  on:
    repo: ${GITHUB_REPO_NAME}
    #    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 3.6 && $TRAVIS_OS_NAME == linux"
  skip_existing: true